### ISSUE TITLE
Planned TODO List

### ISSUE THREAD

**Issue by sidhu-patil** [secanonm/delta_to_html#2]
The planned TODOs are:

- [x] [Delta] Block Elements Problem ||  Done ||
- [x] Order List Index || Done ||
- [x] List With Indentation 
- [x] Performance
